# Generated by Django 4.2.6 on 2023-10-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(verbose_name='Как Вам статья?'),
        ),
    ]
